version: '2.2'
services:
    logstash:
        image: logstash:8.6.2
        depends_on:
          - elasticsearch
        environment:
          XPACK_MONITORING_ENABLED: "false"
          ES_HOST: "elasticsearch:9200"
        ports:
          - "5044:5044/udp"
        volumes:
          - ./deploy/logstash.conf:/config/logstash.conf:ro
          - /tmp/logs/nginx/:/var/log/nginx/:ro
        command: logstash -f /config/logstash.conf
        networks:
          - moves_network

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0-arm64
      environment:
        discovery.type: single-node
      deploy:
        resources:
          limits:
            memory: 4g
      ports:
        - 9200:9200
      volumes:
        - /tmp/esdata:/tmp/elasticsearch/data
      networks:
        - moves_network

    kibana:
      image: docker.elastic.co/kibana/kibana:7.15.0-arm64
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
      networks:
        - moves_network

networks:
  moves_network:
    name: moves_network
    external: true