version: '3.5'

services:

  clickhouse-node1:
    image: lunalabsltd/clickhouse-server:21.7.2.7-arm
    container_name: node1
    hostname: node1
    ports:
      - "9000:9000"
      - "8123:8123"

    volumes:
      - ./data/node1:/etc/clickhouse-server

    networks:
      - moves_network

  clickhouse-node2:
    image: lunalabsltd/clickhouse-server:21.7.2.7-arm
    container_name: node2
    hostname: node2
    volumes:
      - ./data/node2:/etc/clickhouse-server

    ports:
      - "9001:9000"
      - "8124:8123"
    networks:
      - moves_network

  clickhouse-node3:
    image: lunalabsltd/clickhouse-server:21.7.2.7-arm
    container_name: node3
    hostname: node3
    volumes:
      - ./data/node3:/etc/clickhouse-server
    depends_on:
      - zookeeper
    ports:
      - "9002:9000"
      - "8125:8123"
    networks:
      - moves_network

  clickhouse-node4:
    image: lunalabsltd/clickhouse-server:21.7.2.7-arm
    container_name: node4
    hostname: clickhouse-node4
    volumes:
      - ./data/node4:/etc/clickhouse-server
    depends_on:
      - zookeeper
    ports:
      - "9003:9000"
      - "8126:8123"
    networks:
      - moves_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - moves_network

networks:
  moves_network:
    name: moves_network
    external: true