name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  example_matrix:
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wemake-python-styleguide flake8-html lxml mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
         flake8 . --format=html --htmldir output

    - name: mypy
      run: |
         mypy .

    - name: Test with pytest
      run: |
        pytest

